### ISSUE TITLE
Refactor HTML Components

### ISSUE THREAD

**Issue by gkio** [zeriontech/zio.html#1]
should rewrite all components and add for each some description

**Comment by 1755** [comment]
@gkio I think all components could contain next files:
- Component.js (required) – component structure, it should not contain any styles. PropTypes and defaultProps is required.
- ComponentStyles.scss (required) – component styles
- ComponentStyles.js – contains dynamic component styles (if needed)
- Component.tests.js (required) – component unit tests

**Comment by 1755** [comment]
Also I think it makes sense to add `html.scss` for common styles

**Comment by 1755** [comment]
What do you think?

**Comment by gkio** [comment]
@1755 about structure i am already building right you wrote 
about `Also I think it makes sense to add html.scss for common styles` i did not get what you mean
